version: '3'

services:
  cassandra:
    image: cassandra
    container_name: cassandra-container
    ports:
      - "9042:9042"
      - "7001:7001"
      - "9160:9160"
      - "7199:7199"
    environment:
      - CASSANDRA_SEEDS=cassandra
    networks:
      - cassandra-network

networks:
  cassandra-network:
    driver: bridge
