services:
  cassandra-1:
    image: cassandra:latest
    ports:
      - "9042:9042"
    volumes:
      - ./main_schema.cql:/usr/local/bin/main_schema.cql
      - ./insert_data.cql:/usr/local/bin/insert_data.cql
      - ./insert_order_details.cql:/usr/local/bin/insert_order_details.cql
      - ./retrieve_data.cql:/usr/local/bin/retrieve_data.cql
      - ./update_data.cql:/usr/local/bin/update_data.cql
      - ./delete_data.cql:/usr/local/bin/delete_data.cql

networks:
  cassandra-network:
    driver: bridge
