services:
  cassandra-1:
    image: cassandra:latest
    ports:
      - "9042:9042"
    volumes:
      - ./main_schema.cql:/usr/local/bin/main_schema.cql
      - ./execute-cql.sh:/usr/local/bin/execute-cql.sh
  cassandra-2:
    image: cassandra:latest
    ports:
      - "9043:9042"
    volumes:
      - ./main_schema.cql:/usr/local/bin/main_schema.cql
      - ./execute-cql.sh:/usr/local/bin/execute-cql.sh
  cassandra-3:
    image: cassandra:latest
    ports:
      - "9044:9042"
    volumes:
      - ./main_schema.cql:/usr/local/bin/main_schema.cql
      - ./execute-cql.sh:/usr/local/bin/execute-cql.sh

networks:
  cassandra-network:
    driver: bridge
